### get all users
GET http://localhost:7272/shop/v1/allUsers

### register new user
POST http://localhost:7272/shop/v1/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com",
   "password": "userone",
   "picture": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}

### login a user
POST http://localhost:7272/shop/v1/login
Content-Type: application/json

{
    "email": "john@mail.com",
   "password": "userone"
}

###
POST http://localhost:7272/shop/v1/store-image

###
GET http://localhost:7272/uploads/user_images/user.jpg


### admin user
GET http://localhost:7272/api/Alladmin

### login admin
POST http://localhost:7272/api/login
Content-Type: application/json

{
    "email": "abi@mail.com",
   "password": "mainAdmin"
}

### google login
POST http://localhost:7272/shop/v1/googleUser
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com",
    "password": "110044552255886633",
   "picture": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}


